### ISSUE TITLE
Có support SAN Infortrend trong tương lại ko bác

### ISSUE THREAD

**Issue by quangphan1602** [vCloud-DFTBA/san_exporter#16]
Mình thấy hiện tại chưa có hỗ trợ cho San của Infortrend ko biết trong tương lai có dự định update thêm em này ko ạ.

**Comment by HaManhDong** [comment]
Hiện tại bên mình chưa có dòng này nên chưa có plan support. Nhưng nếu bên bạn có thì có thể code thêm driver và contribute cho cộng đồng nha. Ví dụ có sẵn là cái dummy driver nha bạn. :D
